/*
 * Generated by Bluespec Compiler, version 2023.07 (build 0eb551dc)
 * 
 * On Tue Jan  9 16:05:01 CET 2024
 * 
 */
#include "bluesim_primitives.h"
#include "mkGadget.h"


/* Constructor */
MOD_mkGadget::MOD_mkGadget(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_bubble_cycles(simHdl, "bubble_cycles", this, 32u, 0u, (tUInt8)0u),
    INST_infifo(simHdl, "infifo", this, 32u, 2u, (tUInt8)1u, 0u),
    INST_max_bubble_cycles(simHdl, "max_bubble_cycles", this, 32u, 0u, (tUInt8)0u),
    INST_outfifo(simHdl, "outfifo", this, 32u, 2u, (tUInt8)1u, 0u),
    PORT_RST_N((tUInt8)1u)
{
  symbol_count = 7u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkGadget::init_symbols_0()
{
  init_symbol(&symbols[0u], "bubble_cycles", SYM_MODULE, &INST_bubble_cycles);
  init_symbol(&symbols[1u], "infifo", SYM_MODULE, &INST_infifo);
  init_symbol(&symbols[2u], "max_bubble_cycles", SYM_MODULE, &INST_max_bubble_cycles);
  init_symbol(&symbols[3u], "outfifo", SYM_MODULE, &INST_outfifo);
  init_symbol(&symbols[4u], "RL_enqueue_bubble", SYM_RULE);
  init_symbol(&symbols[5u], "RL_enqueue_item", SYM_RULE);
  init_symbol(&symbols[6u], "RL_inc_bubble_cyclus", SYM_RULE);
}


/* Rule actions */

void MOD_mkGadget::RL_enqueue_item()
{
  tUInt32 DEF_infifo_first____d4;
  DEF_infifo_first____d4 = INST_infifo.METH_first();
  INST_outfifo.METH_enq(DEF_infifo_first____d4);
  INST_infifo.METH_deq();
  INST_bubble_cycles.METH_write(0u);
}

void MOD_mkGadget::RL_inc_bubble_cyclus()
{
  tUInt32 DEF_bubble_cycles_PLUS_1___d6;
  DEF_b__h358 = INST_bubble_cycles.METH_read();
  DEF_bubble_cycles_PLUS_1___d6 = DEF_b__h358 + 1u;
  INST_bubble_cycles.METH_write(DEF_bubble_cycles_PLUS_1___d6);
}

void MOD_mkGadget::RL_enqueue_bubble()
{
  tUInt32 DEF_IF_max_bubble_cycles_SLE_bubble_cycles_THEN_bu_ETC___d9;
  tUInt32 DEF_b__h389;
  DEF_b__h389 = INST_max_bubble_cycles.METH_read();
  DEF_b__h358 = INST_bubble_cycles.METH_read();
  DEF_IF_max_bubble_cycles_SLE_bubble_cycles_THEN_bu_ETC___d9 = primSLE8(1u,
									 32u,
									 (tUInt32)(DEF_b__h389),
									 32u,
									 (tUInt32)(DEF_b__h358)) ? DEF_b__h358 : DEF_b__h389;
  INST_outfifo.METH_enq(42u);
  INST_max_bubble_cycles.METH_write(DEF_IF_max_bubble_cycles_SLE_bubble_cycles_THEN_bu_ETC___d9);
}


/* Methods */

void MOD_mkGadget::METH_request_put(tUInt32 ARG_request_put)
{
  INST_infifo.METH_enq(ARG_request_put);
}

tUInt8 MOD_mkGadget::METH_RDY_request_put()
{
  tUInt8 DEF_CAN_FIRE_request_put;
  tUInt8 PORT_RDY_request_put;
  DEF_CAN_FIRE_request_put = INST_infifo.METH_i_notFull();
  PORT_RDY_request_put = DEF_CAN_FIRE_request_put;
  return PORT_RDY_request_put;
}

tUInt32 MOD_mkGadget::METH_response_get()
{
  tUInt32 DEF_response_get__avValue1;
  tUInt32 PORT_response_get;
  DEF_response_get__avValue1 = INST_outfifo.METH_first();
  PORT_response_get = DEF_response_get__avValue1;
  INST_outfifo.METH_deq();
  return PORT_response_get;
}

tUInt8 MOD_mkGadget::METH_RDY_response_get()
{
  tUInt8 DEF_CAN_FIRE_response_get;
  tUInt8 PORT_RDY_response_get;
  DEF_CAN_FIRE_response_get = INST_outfifo.METH_i_notEmpty();
  PORT_RDY_response_get = DEF_CAN_FIRE_response_get;
  return PORT_RDY_response_get;
}


/* Reset routines */

void MOD_mkGadget::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_outfifo.reset_RST(ARG_rst_in);
  INST_max_bubble_cycles.reset_RST(ARG_rst_in);
  INST_infifo.reset_RST(ARG_rst_in);
  INST_bubble_cycles.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkGadget::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkGadget::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_bubble_cycles.dump_state(indent + 2u);
  INST_infifo.dump_state(indent + 2u);
  INST_max_bubble_cycles.dump_state(indent + 2u);
  INST_outfifo.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkGadget::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 6u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h358", 32u);
  num = INST_bubble_cycles.dump_VCD_defs(num);
  num = INST_infifo.dump_VCD_defs(num);
  num = INST_max_bubble_cycles.dump_VCD_defs(num);
  num = INST_outfifo.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkGadget::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkGadget &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkGadget::vcd_defs(tVCDDumpType dt, MOD_mkGadget &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_b__h358) != DEF_b__h358)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h358, 32u);
	backing.DEF_b__h358 = DEF_b__h358;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_b__h358, 32u);
      backing.DEF_b__h358 = DEF_b__h358;
    }
}

void MOD_mkGadget::vcd_prims(tVCDDumpType dt, MOD_mkGadget &backing)
{
  INST_bubble_cycles.dump_VCD(dt, backing.INST_bubble_cycles);
  INST_infifo.dump_VCD(dt, backing.INST_infifo);
  INST_max_bubble_cycles.dump_VCD(dt, backing.INST_max_bubble_cycles);
  INST_outfifo.dump_VCD(dt, backing.INST_outfifo);
}
