/*
 * Generated by Bluespec Compiler, version 2023.07 (build 0eb551dc)
 * 
 * On Sat Jan 13 21:04:30 CET 2024
 * 
 */
#include "bluesim_primitives.h"
#include "mkTb.h"


/* String declarations */
static std::string const __str_literal_2("Counter = %03d, State: IDLE", 27u);
static std::string const __str_literal_3("Counter = %03d, State: STEP1", 28u);
static std::string const __str_literal_4("Counter = %03d, State: STEP2", 28u);
static std::string const __str_literal_5("Counter = %03d, State: STOP", 27u);
static std::string const __str_literal_1("Done", 4u);


/* Constructor */
MOD_mkTb::MOD_mkTb(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_counter(simHdl, "counter", this, 32u, 0u, (tUInt8)0u),
    INST_restart(simHdl, "restart", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_state(simHdl, "state", this, 2u, (tUInt8)0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u)
{
  symbol_count = 8u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkTb::init_symbols_0()
{
  init_symbol(&symbols[0u], "counter", SYM_MODULE, &INST_counter);
  init_symbol(&symbols[1u], "RL_runCounter", SYM_RULE);
  init_symbol(&symbols[2u], "RL_stateIdle", SYM_RULE);
  init_symbol(&symbols[3u], "RL_stateSTOP", SYM_RULE);
  init_symbol(&symbols[4u], "RL_stateStep1", SYM_RULE);
  init_symbol(&symbols[5u], "RL_stateStep2", SYM_RULE);
  init_symbol(&symbols[6u], "restart", SYM_MODULE, &INST_restart);
  init_symbol(&symbols[7u], "state", SYM_MODULE, &INST_state);
}


/* Rule actions */

void MOD_mkTb::RL_runCounter()
{
  tUInt32 DEF_counter_PLUS_1___d3;
  tUInt8 DEF_counter_EQ_200___d2;
  DEF_x__h481 = INST_counter.METH_read();
  DEF_counter_EQ_200___d2 = DEF_x__h481 == 200u;
  DEF_counter_PLUS_1___d3 = DEF_x__h481 + 1u;
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_counter_EQ_200___d2)
      dollar_display(sim_hdl, this, "s", &__str_literal_1);
    if (DEF_counter_EQ_200___d2)
      dollar_finish(sim_hdl, "32", 1u);
  }
  INST_counter.METH_write(DEF_counter_PLUS_1___d3);
}

void MOD_mkTb::RL_stateIdle()
{
  tUInt8 DEF_IF_counter_BIT_31_THEN_NEG_0_CONCAT_IF_counter_ETC___d14;
  tUInt32 DEF__0_CONCAT_IF_counter_BIT_31_THEN_NEG_counter_EL_ETC___d11;
  DEF_x__h481 = INST_counter.METH_read();
  DEF_signed_counter___d6 = DEF_x__h481;
  DEF_counter_BIT_31___h477 = (tUInt8)(DEF_x__h481 >> 31u);
  DEF_IF_counter_BIT_31_THEN_NEG_counter_ELSE_counter___d9 = DEF_counter_BIT_31___h477 ? -DEF_x__h481 : DEF_x__h481;
  DEF__0_CONCAT_IF_counter_BIT_31_THEN_NEG_counter_EL_ETC___d11 = (tUInt32)((tUInt8)((tUInt8)3u & DEF_IF_counter_BIT_31_THEN_NEG_counter_ELSE_counter___d9));
  DEF_IF_counter_BIT_31_THEN_NEG_0_CONCAT_IF_counter_ETC___d14 = (DEF_counter_BIT_31___h477 ? -DEF__0_CONCAT_IF_counter_BIT_31_THEN_NEG_counter_EL_ETC___d11 : DEF__0_CONCAT_IF_counter_BIT_31_THEN_NEG_counter_EL_ETC___d11) == 0u;
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,-32", &__str_literal_2, DEF_signed_counter___d6);
  if (DEF_IF_counter_BIT_31_THEN_NEG_0_CONCAT_IF_counter_ETC___d14)
    INST_state.METH_write((tUInt8)1u);
}

void MOD_mkTb::RL_stateStep1()
{
  tUInt8 DEF_IF_restart_6_THEN_0_ELSE_2___d23;
  tUInt32 DEF__0_CONCAT_IF_counter_BIT_31_THEN_NEG_counter_EL_ETC___d18;
  tUInt8 DEF_restart__h434;
  tUInt8 DEF_restart_6_OR_IF_counter_BIT_31_THEN_NEG_0_CONC_ETC___d22;
  DEF_x__h481 = INST_counter.METH_read();
  DEF_signed_counter___d6 = DEF_x__h481;
  DEF_restart__h434 = INST_restart.METH_read();
  DEF_counter_BIT_31___h477 = (tUInt8)(DEF_x__h481 >> 31u);
  DEF_IF_counter_BIT_31_THEN_NEG_counter_ELSE_counter___d9 = DEF_counter_BIT_31___h477 ? -DEF_x__h481 : DEF_x__h481;
  DEF__0_CONCAT_IF_counter_BIT_31_THEN_NEG_counter_EL_ETC___d18 = (tUInt32)((tUInt8)((tUInt8)7u & DEF_IF_counter_BIT_31_THEN_NEG_counter_ELSE_counter___d9));
  DEF_restart_6_OR_IF_counter_BIT_31_THEN_NEG_0_CONC_ETC___d22 = DEF_restart__h434 || (DEF_counter_BIT_31___h477 ? -DEF__0_CONCAT_IF_counter_BIT_31_THEN_NEG_counter_EL_ETC___d18 : DEF__0_CONCAT_IF_counter_BIT_31_THEN_NEG_counter_EL_ETC___d18) == 0u;
  DEF_IF_restart_6_THEN_0_ELSE_2___d23 = DEF_restart__h434 ? (tUInt8)0u : (tUInt8)2u;
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,-32", &__str_literal_3, DEF_signed_counter___d6);
  if (DEF_restart_6_OR_IF_counter_BIT_31_THEN_NEG_0_CONC_ETC___d22)
    INST_state.METH_write(DEF_IF_restart_6_THEN_0_ELSE_2___d23);
}

void MOD_mkTb::RL_stateStep2()
{
  DEF_x__h481 = INST_counter.METH_read();
  DEF_signed_counter___d6 = DEF_x__h481;
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,-32", &__str_literal_4, DEF_signed_counter___d6);
  INST_state.METH_write((tUInt8)3u);
}

void MOD_mkTb::RL_stateSTOP()
{
  DEF_x__h481 = INST_counter.METH_read();
  DEF_signed_counter___d6 = DEF_x__h481;
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,-32", &__str_literal_5, DEF_signed_counter___d6);
  INST_state.METH_write((tUInt8)0u);
}


/* Methods */


/* Reset routines */

void MOD_mkTb::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_state.reset_RST(ARG_rst_in);
  INST_restart.reset_RST(ARG_rst_in);
  INST_counter.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkTb::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkTb::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_counter.dump_state(indent + 2u);
  INST_restart.dump_state(indent + 2u);
  INST_state.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkTb::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 8u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_counter_BIT_31_THEN_NEG_counter_ELSE_counter___d9", 32u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "counter_BIT_31___h477", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "signed_counter___d6", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h481", 32u);
  num = INST_counter.dump_VCD_defs(num);
  num = INST_restart.dump_VCD_defs(num);
  num = INST_state.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkTb::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTb &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkTb::vcd_defs(tVCDDumpType dt, MOD_mkTb &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_IF_counter_BIT_31_THEN_NEG_counter_ELSE_counter___d9) != DEF_IF_counter_BIT_31_THEN_NEG_counter_ELSE_counter___d9)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_counter_BIT_31_THEN_NEG_counter_ELSE_counter___d9, 32u);
	backing.DEF_IF_counter_BIT_31_THEN_NEG_counter_ELSE_counter___d9 = DEF_IF_counter_BIT_31_THEN_NEG_counter_ELSE_counter___d9;
      }
      ++num;
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_counter_BIT_31___h477) != DEF_counter_BIT_31___h477)
      {
	vcd_write_val(sim_hdl, num, DEF_counter_BIT_31___h477, 1u);
	backing.DEF_counter_BIT_31___h477 = DEF_counter_BIT_31___h477;
      }
      ++num;
      if ((backing.DEF_signed_counter___d6) != DEF_signed_counter___d6)
      {
	vcd_write_val(sim_hdl, num, DEF_signed_counter___d6, 32u);
	backing.DEF_signed_counter___d6 = DEF_signed_counter___d6;
      }
      ++num;
      if ((backing.DEF_x__h481) != DEF_x__h481)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h481, 32u);
	backing.DEF_x__h481 = DEF_x__h481;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_IF_counter_BIT_31_THEN_NEG_counter_ELSE_counter___d9, 32u);
      backing.DEF_IF_counter_BIT_31_THEN_NEG_counter_ELSE_counter___d9 = DEF_IF_counter_BIT_31_THEN_NEG_counter_ELSE_counter___d9;
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_counter_BIT_31___h477, 1u);
      backing.DEF_counter_BIT_31___h477 = DEF_counter_BIT_31___h477;
      vcd_write_val(sim_hdl, num++, DEF_signed_counter___d6, 32u);
      backing.DEF_signed_counter___d6 = DEF_signed_counter___d6;
      vcd_write_val(sim_hdl, num++, DEF_x__h481, 32u);
      backing.DEF_x__h481 = DEF_x__h481;
    }
}

void MOD_mkTb::vcd_prims(tVCDDumpType dt, MOD_mkTb &backing)
{
  INST_counter.dump_VCD(dt, backing.INST_counter);
  INST_restart.dump_VCD(dt, backing.INST_restart);
  INST_state.dump_VCD(dt, backing.INST_state);
}
