/*
 * Generated by Bluespec Compiler, version 2023.07 (build 0eb551dc)
 * 
 * On Mon Nov  6 17:42:19 CET 2023
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkModuleDeepThought.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkModuleDeepThought::MODEL_mkModuleDeepThought()
{
  mkModuleDeepThought_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkModuleDeepThought()
{
  MODEL_mkModuleDeepThought *model = new MODEL_mkModuleDeepThought();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkModuleDeepThought &INST_top = *((MOD_mkModuleDeepThought *)(instance_ptr));
	 if (do_reset_ticks(simHdl))
	 {
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkModuleDeepThought::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkModuleDeepThought_instance = new MOD_mkModuleDeepThought(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkModuleDeepThought_instance->set_clk_0)("CLK");
}
void MODEL_mkModuleDeepThought::destroy_model()
{
  delete mkModuleDeepThought_instance;
  mkModuleDeepThought_instance = NULL;
}
void MODEL_mkModuleDeepThought::reset_model(bool asserted)
{
  (mkModuleDeepThought_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkModuleDeepThought::get_instance()
{
  return mkModuleDeepThought_instance;
}

/* Fill in version numbers */
void MODEL_mkModuleDeepThought::get_version(char const **name, char const **build)
{
  *name = "2023.07";
  *build = "0eb551dc";
}

/* Get the model creation time */
time_t MODEL_mkModuleDeepThought::get_creation_time()
{
  
  /* Mon Nov  6 16:42:19 UTC 2023 */
  return 1699288939llu;
}

/* State dumping function */
void MODEL_mkModuleDeepThought::dump_state()
{
  (mkModuleDeepThought_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkModuleDeepThought & mkModuleDeepThought_backing(tSimStateHdl simHdl)
{
  static MOD_mkModuleDeepThought *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkModuleDeepThought(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkModuleDeepThought::dump_VCD_defs()
{
  (mkModuleDeepThought_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkModuleDeepThought::dump_VCD(tVCDDumpType dt)
{
  (mkModuleDeepThought_instance->dump_VCD)(dt,
					   vcd_depth(sim_hdl),
					   mkModuleDeepThought_backing(sim_hdl));
}
