/*
 * Generated by Bluespec Compiler, version 2023.07 (build 0eb551dc)
 * 
 * On Fri Feb 23 21:28:46 CET 2024
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkTB2.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkTB2::MODEL_mkTB2()
{
  mkTB2_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkTB2()
{
  MODEL_mkTB2 *model = new MODEL_mkTB2();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkTB2 &INST_top = *((MOD_mkTB2 *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2_3_A_ETC___d79;
	 tUInt8 DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2_3_A_ETC___d89;
	 tUInt8 DEF_INST_top_DEF_NOT_jj_repeat_count_read__5_BIT_0_6___d77;
	 tUInt8 DEF_INST_top_DEF_counter_5_SLT_8___d96;
	 tUInt8 DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2_3_A_ETC___d115;
	 tUInt8 DEF_INST_top_DEF_NOT_jj_1_repeat_count_read__7_BIT_0_8___d99;
	 tUInt8 DEF_INST_top_DEF_counter_5_SLT_8_6_AND_jj_1_repeat_count_read___ETC___d106;
	 tUInt8 DEF_INST_top_DEF_NOT_counter_5_SLT_8_6___d132;
	 tUInt8 DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2_3_A_ETC___d146;
	 tUInt8 DEF_INST_top_DEF_NOT_jj_2_repeat_count_read__33_BIT_0_34___d135;
	 tUInt8 DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2_3_A_ETC___d104;
	 tUInt8 DEF_INST_top_DEF_abort_whas__9_AND_abort_wget__0_1_OR_state_mkF_ETC___d177;
	 tUInt8 DEF_INST_top_DEF_abort_whas__9_AND_abort_wget__0_1_OR_state_mkF_ETC___d181;
	 tUInt8 DEF_INST_top_DEF_abort_whas__9_AND_abort_wget__0___d31;
	 tUInt8 DEF_INST_top_DEF_NOT_start_wire_whas__2_3_OR_NOT_start_wire_wge_ETC___d36;
	 tUInt8 DEF_INST_top_DEF_abort_whas__9_AND_abort_wget__0_1_OR_state_mkF_ETC___d60;
	 tUInt8 DEF_INST_top_DEF_start_wire_whas__2_AND_start_wire_wget__4___d55;
	 tUInt8 DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2___d53;
	 tUInt8 DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2_3_O_ETC___d81;
	 tUInt8 DEF_INST_top_DEF_NOT_jj_repeat_count_read__5_BIT_0_6_7_AND_NOT__ETC___d90;
	 tUInt8 DEF_INST_top_DEF_jj_repeat_count_read__5_BIT_0_6_AND_NOT_abort__ETC___d85;
	 tUInt8 DEF_INST_top_DEF_counter_5_SLT_8_6_AND_jj_1_repeat_count_read___ETC___d111;
	 tUInt8 DEF_INST_top_DEF_NOT_jj_1_repeat_count_read__7_BIT_0_8_9_AND_NO_ETC___d116;
	 tUInt8 DEF_INST_top_DEF_counter_5_SLT_8_6_AND_jj_1_repeat_count_read___ETC___d120;
	 tUInt8 DEF_INST_top_DEF_NOT_counter_5_SLT_8_6_32_AND_jj_2_repeat_count_ETC___d139;
	 tUInt8 DEF_INST_top_DEF_NOT_jj_2_repeat_count_read__33_BIT_0_34_35_AND_ETC___d147;
	 tUInt8 DEF_INST_top_DEF_state_mkFSMstate_read__6_EQ_9___d101;
	 tUInt8 DEF_INST_top_DEF_state_mkFSMstate_read__6_EQ_14___d102;
	 tUInt8 DEF_INST_top_DEF_state_mkFSMstate_read__6_EQ_15___d140;
	 tUInt8 DEF_INST_top_DEF_state_mkFSMstate_read__6_EQ_19___d59;
	 tUInt8 DEF_INST_top_DEF_dut_ticks_EQ_0___d2;
	 tUInt8 DEF_INST_top_DEF_jj_repeat_count_read__5_BIT_0___d76;
	 tUInt8 DEF_INST_top_DEF_jj_1_repeat_count_read__7_BIT_0___d98;
	 tUInt8 DEF_INST_top_DEF_jj_2_repeat_count_read__33_BIT_0___d134;
	 tUInt8 DEF_INST_top_DEF_abort_wget____d30;
	 tUInt8 DEF_INST_top_DEF_abort_whas____d29;
	 tUInt8 DEF_INST_top_DEF_start_reg__h79225;
	 tUInt8 DEF_INST_top_DEF_running__h79311;
	 tUInt8 DEF_INST_top_DEF_start_wire_wget____d34;
	 tUInt8 DEF_INST_top_DEF_start_wire_whas____d32;
	 tUInt8 DEF_INST_top_DEF_dut_fifo_i_notEmpty____d11;
	 tUInt8 DEF_INST_top_DEF_start_reg_1__h71369;
	 tUInt8 DEF_INST_top_DEF_state_fired__h71371;
	 tUInt8 DEF_INST_top_DEF_x__h697;
	 tUInt8 DEF_INST_top_DEF_state_mkFSMstate_read____d56;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_dut_ticrule;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_dut_ticrule;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_dut_idle;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_dut_idle;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_dut_start;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_dut_start;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_dut_transfer;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_dut_transfer;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_dut_ende;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_dut_ende;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_start_reg__dreg_update;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_start_reg__dreg_update;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_state_handle_abort;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_state_handle_abort;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_state_fired__dreg_update;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_state_fired__dreg_update;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_state_every;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_state_every;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_restart;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_restart;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l151c13;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l152c13;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l159c16;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l160c13;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l166c13;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l166c25;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_f_init_l173c13;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l174c17;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l174c29;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_f_update_l173c13;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l185c13;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l185c25;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l193c13;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l166c13;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_action_ovlp_r_update_l166c13;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l174c17;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_action_ovlp_r_update_l174c17;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l185c13;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_action_ovlp_r_update_l185c13;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_idle_l150c18;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_idle_l150c18;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_fsm_start;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_fsm_start;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_auto_start;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_auto_start;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_auto_finish;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_auto_finish;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_10;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_10;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_11;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_12;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_12;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_13;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_13;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_14;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_14;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_15;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_15;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_16;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_16;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_17;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_17;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_18;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_18;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_19;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_19;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_20;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_20;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_21;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_21;
	 INST_top.DEF_jj_repeat_count_read____d75 = INST_top.INST_jj_repeat_count.METH_read();
	 DEF_INST_top_DEF_state_mkFSMstate_read____d56 = INST_top.INST_state_mkFSMstate.METH_read();
	 DEF_INST_top_DEF_abort_whas____d29 = INST_top.INST_abort.METH_whas();
	 DEF_INST_top_DEF_abort_wget____d30 = INST_top.INST_abort.METH_wget();
	 DEF_INST_top_DEF_jj_repeat_count_read__5_BIT_0___d76 = (tUInt8)((tUInt8)1u & (INST_top.DEF_jj_repeat_count_read____d75));
	 DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2___d53 = !DEF_INST_top_DEF_abort_whas____d29 || !DEF_INST_top_DEF_abort_wget____d30;
	 DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2_3_A_ETC___d89 = DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2___d53 && DEF_INST_top_DEF_state_mkFSMstate_read____d56 == (tUInt8)7u;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_f_init_l173c13 = DEF_INST_top_DEF_jj_repeat_count_read__5_BIT_0___d76 && DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2_3_A_ETC___d89;
	 INST_top.DEF_WILL_FIRE_RL_action_f_init_l173c13 = DEF_INST_top_DEF_CAN_FIRE_RL_action_f_init_l173c13;
	 INST_top.DEF_jj_1_repeat_count_read____d97 = INST_top.INST_jj_1_repeat_count.METH_read();
	 DEF_INST_top_DEF_jj_1_repeat_count_read__7_BIT_0___d98 = (tUInt8)((tUInt8)1u & (INST_top.DEF_jj_1_repeat_count_read____d97));
	 DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2_3_A_ETC___d115 = DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2___d53 && DEF_INST_top_DEF_state_mkFSMstate_read____d56 == (tUInt8)12u;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_f_update_l173c13 = DEF_INST_top_DEF_jj_1_repeat_count_read__7_BIT_0___d98 && DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2_3_A_ETC___d115;
	 INST_top.DEF_WILL_FIRE_RL_action_f_update_l173c13 = DEF_INST_top_DEF_CAN_FIRE_RL_action_f_update_l173c13;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l152c13 = DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2___d53 && DEF_INST_top_DEF_state_mkFSMstate_read____d56 == (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_action_l152c13 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l152c13;
	 INST_top.DEF_dut_pinvalue__h77760 = INST_top.INST_dut_pinvalue.METH_read();
	 INST_top.DEF_NOT_dut_pinvalue_4___d65 = !(INST_top.DEF_dut_pinvalue__h77760);
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l160c13 = INST_top.DEF_NOT_dut_pinvalue_4___d65 && (DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2___d53 && DEF_INST_top_DEF_state_mkFSMstate_read____d56 == (tUInt8)3u);
	 INST_top.DEF_WILL_FIRE_RL_action_l160c13 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l160c13;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l159c16 = INST_top.INST_dut_fifo.METH_i_notFull() && (DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2___d53 && DEF_INST_top_DEF_state_mkFSMstate_read____d56 == (tUInt8)2u);
	 INST_top.DEF_WILL_FIRE_RL_action_l159c16 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l159c16;
	 INST_top.DEF_jj_2_repeat_count_read____d133 = INST_top.INST_jj_2_repeat_count.METH_read();
	 DEF_INST_top_DEF_jj_2_repeat_count_read__33_BIT_0___d134 = (tUInt8)((tUInt8)1u & (INST_top.DEF_jj_2_repeat_count_read____d133));
	 DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2_3_A_ETC___d146 = DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2___d53 && DEF_INST_top_DEF_state_mkFSMstate_read____d56 == (tUInt8)17u;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l193c13 = DEF_INST_top_DEF_jj_2_repeat_count_read__33_BIT_0___d134 && DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2_3_A_ETC___d146;
	 INST_top.DEF_WILL_FIRE_RL_action_l193c13 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l193c13;
	 INST_top.DEF_state_can_overlap__h7065 = INST_top.INST_state_can_overlap.METH_read();
	 DEF_INST_top_DEF_NOT_jj_repeat_count_read__5_BIT_0_6___d77 = !DEF_INST_top_DEF_jj_repeat_count_read__5_BIT_0___d76;
	 DEF_INST_top_DEF_NOT_jj_repeat_count_read__5_BIT_0_6_7_AND_NOT__ETC___d90 = DEF_INST_top_DEF_NOT_jj_repeat_count_read__5_BIT_0_6___d77 && DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2_3_A_ETC___d89;
	 DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2_3_A_ETC___d79 = DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2___d53 && DEF_INST_top_DEF_state_mkFSMstate_read____d56 == (tUInt8)4u;
	 DEF_INST_top_DEF_jj_repeat_count_read__5_BIT_0_6_AND_NOT_abort__ETC___d85 = (DEF_INST_top_DEF_jj_repeat_count_read__5_BIT_0___d76 && DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2_3_A_ETC___d79) || (DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2___d53 && DEF_INST_top_DEF_state_mkFSMstate_read____d56 == (tUInt8)5u);
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l166c13 = INST_top.DEF_state_can_overlap__h7065 && (DEF_INST_top_DEF_jj_repeat_count_read__5_BIT_0_6_AND_NOT_abort__ETC___d85 || DEF_INST_top_DEF_NOT_jj_repeat_count_read__5_BIT_0_6_7_AND_NOT__ETC___d90);
	 DEF_INST_top_DEF_WILL_FIRE_RL_action_ovlp_r_update_l166c13 = DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l166c13;
	 INST_top.DEF_x__h75662 = INST_top.INST_counter.METH_read();
	 DEF_INST_top_DEF_state_mkFSMstate_read__6_EQ_14___d102 = DEF_INST_top_DEF_state_mkFSMstate_read____d56 == (tUInt8)14u;
	 DEF_INST_top_DEF_state_mkFSMstate_read__6_EQ_9___d101 = DEF_INST_top_DEF_state_mkFSMstate_read____d56 == (tUInt8)9u;
	 DEF_INST_top_DEF_NOT_jj_1_repeat_count_read__7_BIT_0_8___d99 = !DEF_INST_top_DEF_jj_1_repeat_count_read__7_BIT_0___d98;
	 DEF_INST_top_DEF_NOT_jj_1_repeat_count_read__7_BIT_0_8_9_AND_NO_ETC___d116 = DEF_INST_top_DEF_NOT_jj_1_repeat_count_read__7_BIT_0_8___d99 && DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2_3_A_ETC___d115;
	 DEF_INST_top_DEF_counter_5_SLT_8___d96 = primSLT8(1u,
							   32u,
							   (tUInt32)(INST_top.DEF_x__h75662),
							   32u,
							   8u);
	 DEF_INST_top_DEF_counter_5_SLT_8_6_AND_jj_1_repeat_count_read___ETC___d106 = DEF_INST_top_DEF_counter_5_SLT_8___d96 && DEF_INST_top_DEF_jj_1_repeat_count_read__7_BIT_0___d98;
	 DEF_INST_top_DEF_counter_5_SLT_8_6_AND_jj_1_repeat_count_read___ETC___d120 = DEF_INST_top_DEF_counter_5_SLT_8_6_AND_jj_1_repeat_count_read___ETC___d106 && (DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2___d53 && DEF_INST_top_DEF_state_mkFSMstate_read__6_EQ_14___d102);
	 DEF_INST_top_DEF_counter_5_SLT_8_6_AND_jj_1_repeat_count_read___ETC___d111 = (DEF_INST_top_DEF_counter_5_SLT_8_6_AND_jj_1_repeat_count_read___ETC___d106 && (DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2___d53 && DEF_INST_top_DEF_state_mkFSMstate_read__6_EQ_9___d101)) || (DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2___d53 && DEF_INST_top_DEF_state_mkFSMstate_read____d56 == (tUInt8)10u);
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l174c17 = INST_top.DEF_state_can_overlap__h7065 && (DEF_INST_top_DEF_counter_5_SLT_8_6_AND_jj_1_repeat_count_read___ETC___d111 || (DEF_INST_top_DEF_NOT_jj_1_repeat_count_read__7_BIT_0_8_9_AND_NO_ETC___d116 || DEF_INST_top_DEF_counter_5_SLT_8_6_AND_jj_1_repeat_count_read___ETC___d120));
	 DEF_INST_top_DEF_WILL_FIRE_RL_action_ovlp_r_update_l174c17 = DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l174c17;
	 DEF_INST_top_DEF_state_mkFSMstate_read__6_EQ_15___d140 = DEF_INST_top_DEF_state_mkFSMstate_read____d56 == (tUInt8)15u;
	 DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2_3_A_ETC___d104 = DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2___d53 && (DEF_INST_top_DEF_state_mkFSMstate_read__6_EQ_9___d101 || DEF_INST_top_DEF_state_mkFSMstate_read__6_EQ_14___d102);
	 DEF_INST_top_DEF_NOT_jj_2_repeat_count_read__33_BIT_0_34___d135 = !DEF_INST_top_DEF_jj_2_repeat_count_read__33_BIT_0___d134;
	 DEF_INST_top_DEF_NOT_jj_2_repeat_count_read__33_BIT_0_34_35_AND_ETC___d147 = DEF_INST_top_DEF_NOT_jj_2_repeat_count_read__33_BIT_0_34___d135 && DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2_3_A_ETC___d146;
	 DEF_INST_top_DEF_NOT_counter_5_SLT_8_6___d132 = !DEF_INST_top_DEF_counter_5_SLT_8___d96;
	 DEF_INST_top_DEF_NOT_counter_5_SLT_8_6_32_AND_jj_2_repeat_count_ETC___d139 = (DEF_INST_top_DEF_NOT_counter_5_SLT_8_6___d132 && DEF_INST_top_DEF_jj_2_repeat_count_read__33_BIT_0___d134) && DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2_3_A_ETC___d104;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l185c13 = INST_top.DEF_state_can_overlap__h7065 && (DEF_INST_top_DEF_NOT_counter_5_SLT_8_6_32_AND_jj_2_repeat_count_ETC___d139 || ((DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2___d53 && DEF_INST_top_DEF_state_mkFSMstate_read__6_EQ_15___d140) || DEF_INST_top_DEF_NOT_jj_2_repeat_count_read__33_BIT_0_34_35_AND_ETC___d147));
	 DEF_INST_top_DEF_WILL_FIRE_RL_action_ovlp_r_update_l185c13 = DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l185c13;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l166c13 = DEF_INST_top_DEF_NOT_jj_repeat_count_read__5_BIT_0_6___d77 && DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2_3_A_ETC___d79;
	 INST_top.DEF_WILL_FIRE_RL_action_r_init_l166c13 = DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l166c13;
	 DEF_INST_top_DEF_state_fired__h71371 = INST_top.INST_state_fired.METH_read();
	 DEF_INST_top_DEF_start_reg_1__h71369 = INST_top.INST_start_reg_1.METH_read();
	 DEF_INST_top_DEF_running__h79311 = INST_top.INST_running.METH_read();
	 DEF_INST_top_DEF_start_reg__h79225 = INST_top.INST_start_reg.METH_read();
	 DEF_INST_top_DEF_state_mkFSMstate_read__6_EQ_19___d59 = DEF_INST_top_DEF_state_mkFSMstate_read____d56 == (tUInt8)19u;
	 DEF_INST_top_DEF_abort_whas__9_AND_abort_wget__0___d31 = DEF_INST_top_DEF_abort_whas____d29 && DEF_INST_top_DEF_abort_wget____d30;
	 DEF_INST_top_DEF_abort_whas__9_AND_abort_wget__0_1_OR_state_mkF_ETC___d60 = (DEF_INST_top_DEF_abort_whas__9_AND_abort_wget__0___d31 || DEF_INST_top_DEF_state_mkFSMstate_read____d56 == (tUInt8)0u) || DEF_INST_top_DEF_state_mkFSMstate_read__6_EQ_19___d59;
	 DEF_INST_top_DEF_abort_whas__9_AND_abort_wget__0_1_OR_state_mkF_ETC___d177 = DEF_INST_top_DEF_abort_whas__9_AND_abort_wget__0_1_OR_state_mkF_ETC___d60 && (!DEF_INST_top_DEF_start_reg_1__h71369 || DEF_INST_top_DEF_state_fired__h71371);
	 DEF_INST_top_DEF_abort_whas__9_AND_abort_wget__0_1_OR_state_mkF_ETC___d181 = DEF_INST_top_DEF_abort_whas__9_AND_abort_wget__0_1_OR_state_mkF_ETC___d177 && !DEF_INST_top_DEF_start_reg__h79225;
	 DEF_INST_top_DEF_CAN_FIRE_RL_auto_finish = DEF_INST_top_DEF_running__h79311 && DEF_INST_top_DEF_abort_whas__9_AND_abort_wget__0_1_OR_state_mkF_ETC___d181;
	 DEF_INST_top_DEF_WILL_FIRE_RL_auto_finish = DEF_INST_top_DEF_CAN_FIRE_RL_auto_finish;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l174c17 = (DEF_INST_top_DEF_counter_5_SLT_8___d96 && DEF_INST_top_DEF_NOT_jj_1_repeat_count_read__7_BIT_0_8___d99) && DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2_3_A_ETC___d104;
	 INST_top.DEF_WILL_FIRE_RL_action_r_init_l174c17 = DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l174c17;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l185c13 = (DEF_INST_top_DEF_NOT_counter_5_SLT_8_6___d132 && DEF_INST_top_DEF_NOT_jj_2_repeat_count_read__33_BIT_0_34___d135) && DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2_3_A_ETC___d104;
	 INST_top.DEF_WILL_FIRE_RL_action_r_init_l185c13 = DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l185c13;
	 DEF_INST_top_DEF_CAN_FIRE_RL_auto_start = DEF_INST_top_DEF_abort_whas__9_AND_abort_wget__0_1_OR_state_mkF_ETC___d181 && !DEF_INST_top_DEF_running__h79311;
	 DEF_INST_top_DEF_WILL_FIRE_RL_auto_start = DEF_INST_top_DEF_CAN_FIRE_RL_auto_start;
	 INST_top.DEF_b__h317 = INST_top.INST_dut_ticks.METH_read();
	 DEF_INST_top_DEF_x__h697 = INST_top.INST_dut_state.METH_read();
	 DEF_INST_top_DEF_dut_fifo_i_notEmpty____d11 = INST_top.INST_dut_fifo.METH_i_notEmpty();
	 DEF_INST_top_DEF_dut_ticks_EQ_0___d2 = (INST_top.DEF_b__h317) == 0u;
	 DEF_INST_top_DEF_CAN_FIRE_RL_dut_ende = DEF_INST_top_DEF_dut_fifo_i_notEmpty____d11 && (DEF_INST_top_DEF_x__h697 == (tUInt8)3u && DEF_INST_top_DEF_dut_ticks_EQ_0___d2);
	 DEF_INST_top_DEF_WILL_FIRE_RL_dut_ende = DEF_INST_top_DEF_CAN_FIRE_RL_dut_ende;
	 DEF_INST_top_DEF_CAN_FIRE_RL_dut_idle = DEF_INST_top_DEF_x__h697 == (tUInt8)0u && DEF_INST_top_DEF_dut_ticks_EQ_0___d2;
	 DEF_INST_top_DEF_WILL_FIRE_RL_dut_idle = DEF_INST_top_DEF_CAN_FIRE_RL_dut_idle;
	 DEF_INST_top_DEF_CAN_FIRE_RL_dut_start = DEF_INST_top_DEF_x__h697 == (tUInt8)1u && DEF_INST_top_DEF_dut_ticks_EQ_0___d2;
	 DEF_INST_top_DEF_WILL_FIRE_RL_dut_start = DEF_INST_top_DEF_CAN_FIRE_RL_dut_start;
	 DEF_INST_top_DEF_CAN_FIRE_RL_dut_ticrule = !DEF_INST_top_DEF_dut_ticks_EQ_0___d2;
	 DEF_INST_top_DEF_WILL_FIRE_RL_dut_ticrule = DEF_INST_top_DEF_CAN_FIRE_RL_dut_ticrule;
	 DEF_INST_top_DEF_CAN_FIRE_RL_dut_transfer = DEF_INST_top_DEF_dut_fifo_i_notEmpty____d11 && (DEF_INST_top_DEF_x__h697 == (tUInt8)2u && DEF_INST_top_DEF_dut_ticks_EQ_0___d2);
	 DEF_INST_top_DEF_WILL_FIRE_RL_dut_transfer = DEF_INST_top_DEF_CAN_FIRE_RL_dut_transfer;
	 DEF_INST_top_DEF_CAN_FIRE_RL_fsm_start = DEF_INST_top_DEF_abort_whas__9_AND_abort_wget__0_1_OR_state_mkF_ETC___d177 && DEF_INST_top_DEF_start_reg__h79225;
	 DEF_INST_top_DEF_WILL_FIRE_RL_fsm_start = DEF_INST_top_DEF_CAN_FIRE_RL_fsm_start;
	 DEF_INST_top_DEF_CAN_FIRE_RL_restart = (DEF_INST_top_DEF_start_reg_1__h71369 && !DEF_INST_top_DEF_state_fired__h71371) && DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2___d53;
	 DEF_INST_top_DEF_WILL_FIRE_RL_restart = DEF_INST_top_DEF_CAN_FIRE_RL_restart;
	 DEF_INST_top_DEF_CAN_FIRE_RL_start_reg__dreg_update = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_start_reg__dreg_update = DEF_INST_top_DEF_CAN_FIRE_RL_start_reg__dreg_update;
	 DEF_INST_top_DEF_CAN_FIRE_RL_state_every = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_state_every = DEF_INST_top_DEF_CAN_FIRE_RL_state_every;
	 DEF_INST_top_DEF_CAN_FIRE_RL_state_fired__dreg_update = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_state_fired__dreg_update = DEF_INST_top_DEF_CAN_FIRE_RL_state_fired__dreg_update;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_10 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_10 = DEF_INST_top_DEF_CAN_FIRE___me_check_10;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_11 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_11 = DEF_INST_top_DEF_CAN_FIRE___me_check_11;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_12 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_12 = DEF_INST_top_DEF_CAN_FIRE___me_check_12;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_13 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_13 = DEF_INST_top_DEF_CAN_FIRE___me_check_13;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_14 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_14 = DEF_INST_top_DEF_CAN_FIRE___me_check_14;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_15 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_15 = DEF_INST_top_DEF_CAN_FIRE___me_check_15;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_16 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_16 = DEF_INST_top_DEF_CAN_FIRE___me_check_16;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_17 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_17 = DEF_INST_top_DEF_CAN_FIRE___me_check_17;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_18 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_18 = DEF_INST_top_DEF_CAN_FIRE___me_check_18;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_19 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_19 = DEF_INST_top_DEF_CAN_FIRE___me_check_19;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_20 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_20 = DEF_INST_top_DEF_CAN_FIRE___me_check_20;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_21 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_21 = DEF_INST_top_DEF_CAN_FIRE___me_check_21;
	 if (INST_top.DEF_WILL_FIRE_RL_action_f_init_l173c13)
	   INST_top.RL_action_f_init_l173c13();
	 if (INST_top.DEF_WILL_FIRE_RL_action_f_update_l173c13)
	   INST_top.RL_action_f_update_l173c13();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l152c13)
	   INST_top.RL_action_l152c13();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l160c13)
	   INST_top.RL_action_l160c13();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l193c13)
	   INST_top.RL_action_l193c13();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_action_ovlp_r_update_l166c13)
	   INST_top.RL_action_ovlp_r_update_l166c13();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_action_ovlp_r_update_l174c17)
	   INST_top.RL_action_ovlp_r_update_l174c17();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_action_ovlp_r_update_l185c13)
	   INST_top.RL_action_ovlp_r_update_l185c13();
	 if (INST_top.DEF_WILL_FIRE_RL_action_r_init_l166c13)
	   INST_top.RL_action_r_init_l166c13();
	 if (INST_top.DEF_WILL_FIRE_RL_action_r_init_l174c17)
	   INST_top.RL_action_r_init_l174c17();
	 if (INST_top.DEF_WILL_FIRE_RL_action_r_init_l185c13)
	   INST_top.RL_action_r_init_l185c13();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_auto_start)
	   INST_top.RL_auto_start();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_dut_ticrule)
	   INST_top.RL_dut_ticrule();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_fsm_start)
	   INST_top.RL_fsm_start();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_restart)
	   INST_top.RL_restart();
	 DEF_INST_top_DEF_start_wire_whas____d32 = INST_top.INST_start_wire.METH_whas();
	 DEF_INST_top_DEF_start_wire_wget____d34 = INST_top.INST_start_wire.METH_wget();
	 DEF_INST_top_DEF_start_wire_whas__2_AND_start_wire_wget__4___d55 = DEF_INST_top_DEF_start_wire_whas____d32 && DEF_INST_top_DEF_start_wire_wget____d34;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l151c13 = (DEF_INST_top_DEF_start_wire_whas__2_AND_start_wire_wget__4___d55 && DEF_INST_top_DEF_abort_whas__9_AND_abort_wget__0_1_OR_state_mkF_ETC___d60) && !((((DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l185c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l174c17) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l166c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l193c13)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l185c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_f_update_l173c13) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l174c17 || DEF_INST_top_DEF_CAN_FIRE_RL_action_f_init_l173c13))) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l166c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l160c13) || DEF_INST_top_DEF_CAN_FIRE_RL_action_l152c13));
	 INST_top.DEF_WILL_FIRE_RL_action_l151c13 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l151c13;
	 DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2_3_O_ETC___d81 = DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2___d53 || DEF_INST_top_DEF_start_wire_whas__2_AND_start_wire_wget__4___d55;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l166c25 = (DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2_3_O_ETC___d81 && (DEF_INST_top_DEF_jj_repeat_count_read__5_BIT_0_6_AND_NOT_abort__ETC___d85 || ((DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2___d53 && DEF_INST_top_DEF_state_mkFSMstate_read____d56 == (tUInt8)6u) || DEF_INST_top_DEF_NOT_jj_repeat_count_read__5_BIT_0_6_7_AND_NOT__ETC___d90))) && !((((DEF_INST_top_DEF_CAN_FIRE_RL_auto_start || DEF_INST_top_DEF_CAN_FIRE_RL_fsm_start) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l185c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l174c17)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_l193c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l185c13) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_f_update_l173c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l174c17))) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_f_init_l173c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l166c13) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l160c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l152c13)));
	 INST_top.DEF_WILL_FIRE_RL_action_l166c25 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l166c25;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l174c29 = (DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2_3_O_ETC___d81 && ((DEF_INST_top_DEF_counter_5_SLT_8_6_AND_jj_1_repeat_count_read___ETC___d111 || ((DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2___d53 && DEF_INST_top_DEF_state_mkFSMstate_read____d56 == (tUInt8)11u) || DEF_INST_top_DEF_NOT_jj_1_repeat_count_read__7_BIT_0_8_9_AND_NO_ETC___d116)) || DEF_INST_top_DEF_counter_5_SLT_8_6_AND_jj_1_repeat_count_read___ETC___d120)) && !((((DEF_INST_top_DEF_CAN_FIRE_RL_auto_start || DEF_INST_top_DEF_CAN_FIRE_RL_fsm_start) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l185c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l166c13)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_l193c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l185c13) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_f_update_l173c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l174c17))) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_f_init_l173c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l166c13) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l160c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l152c13)));
	 INST_top.DEF_WILL_FIRE_RL_action_l174c29 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l174c29;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l185c25 = (DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2_3_O_ETC___d81 && ((DEF_INST_top_DEF_NOT_counter_5_SLT_8_6_32_AND_jj_2_repeat_count_ETC___d139 || (DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2___d53 && (DEF_INST_top_DEF_state_mkFSMstate_read__6_EQ_15___d140 || DEF_INST_top_DEF_state_mkFSMstate_read____d56 == (tUInt8)16u))) || DEF_INST_top_DEF_NOT_jj_2_repeat_count_read__33_BIT_0_34_35_AND_ETC___d147)) && !((((DEF_INST_top_DEF_CAN_FIRE_RL_auto_start || DEF_INST_top_DEF_CAN_FIRE_RL_fsm_start) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l174c17 || DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l166c13)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_l193c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l185c13) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_f_update_l173c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l174c17))) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_f_init_l173c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l166c13) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l160c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l152c13)));
	 INST_top.DEF_WILL_FIRE_RL_action_l185c25 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l185c25;
	 DEF_INST_top_DEF_NOT_start_wire_whas__2_3_OR_NOT_start_wire_wge_ETC___d36 = !DEF_INST_top_DEF_start_wire_whas____d32 || !DEF_INST_top_DEF_start_wire_wget____d34;
	 DEF_INST_top_DEF_CAN_FIRE_RL_state_handle_abort = (DEF_INST_top_DEF_abort_whas__9_AND_abort_wget__0___d31 && DEF_INST_top_DEF_NOT_start_wire_whas__2_3_OR_NOT_start_wire_wge_ETC___d36) && !((((DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l185c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l174c17) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l166c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l193c13)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l185c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_f_update_l173c13) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l174c17 || DEF_INST_top_DEF_CAN_FIRE_RL_action_f_init_l173c13))) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l166c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l160c13) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l152c13 || DEF_INST_top_DEF_CAN_FIRE_RL_restart)));
	 DEF_INST_top_DEF_WILL_FIRE_RL_state_handle_abort = DEF_INST_top_DEF_CAN_FIRE_RL_state_handle_abort;
	 DEF_INST_top_DEF_CAN_FIRE_RL_idle_l150c18 = (DEF_INST_top_DEF_NOT_start_wire_whas__2_3_OR_NOT_start_wire_wge_ETC___d36 && (DEF_INST_top_DEF_NOT_abort_whas__9_1_OR_NOT_abort_wget__0_2___d53 && DEF_INST_top_DEF_state_mkFSMstate_read__6_EQ_19___d59)) && !((((DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l185c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l174c17) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l166c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l193c13)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l185c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_f_update_l173c13) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l174c17 || DEF_INST_top_DEF_CAN_FIRE_RL_action_f_init_l173c13))) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l166c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l160c13) || DEF_INST_top_DEF_CAN_FIRE_RL_action_l152c13));
	 DEF_INST_top_DEF_WILL_FIRE_RL_idle_l150c18 = DEF_INST_top_DEF_CAN_FIRE_RL_idle_l150c18;
	 if (INST_top.DEF_WILL_FIRE_RL_action_l151c13)
	   INST_top.RL_action_l151c13();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l166c25)
	   INST_top.RL_action_l166c25();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l174c29)
	   INST_top.RL_action_l174c29();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l185c25)
	   INST_top.RL_action_l185c25();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_auto_finish)
	   INST_top.RL_auto_finish();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_dut_ende)
	   INST_top.RL_dut_ende();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_dut_idle)
	   INST_top.RL_dut_idle();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l159c16)
	   INST_top.RL_action_l159c16();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_dut_transfer)
	   INST_top.RL_dut_transfer();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_start_reg__dreg_update)
	   INST_top.RL_start_reg__dreg_update();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_state_handle_abort)
	   INST_top.RL_state_handle_abort();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_10)
	   INST_top.__me_check_10();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_11)
	   INST_top.__me_check_11();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_12)
	   INST_top.__me_check_12();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_dut_start)
	   INST_top.RL_dut_start();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_13)
	   INST_top.__me_check_13();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_14)
	   INST_top.__me_check_14();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_15)
	   INST_top.__me_check_15();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_16)
	   INST_top.__me_check_16();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_17)
	   INST_top.__me_check_17();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_18)
	   INST_top.__me_check_18();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_20)
	   INST_top.__me_check_20();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_19)
	   INST_top.__me_check_19();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_21)
	   INST_top.__me_check_21();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_idle_l150c18)
	   INST_top.RL_idle_l150c18();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_state_every)
	   INST_top.RL_state_every();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_state_fired__dreg_update)
	   INST_top.RL_state_fired__dreg_update();
	 INST_top.INST_state_fired_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_state_overlap_pw.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_state_set_pw.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_abort.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_start_reg_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_start_wire.clk((tUInt8)1u, (tUInt8)1u);
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_dut_pinvalue.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut_ctr.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut_fifo.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_dut_state.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut_ticks.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_counter.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mistakes.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_start_reg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_start_reg_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_jj_repeat_count.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_jj_1_repeat_count.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_jj_2_repeat_count.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_state_mkFSMstate.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_state_fired.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_state_can_overlap.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_running.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkTB2::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkTB2_instance = new MOD_mkTB2(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkTB2_instance->INST_dut_fifo.set_clk_0)("CLK");
  (mkTB2_instance->INST_start_wire.set_clk_0)("CLK");
  (mkTB2_instance->INST_start_reg_2.set_clk_0)("CLK");
  (mkTB2_instance->INST_abort.set_clk_0)("CLK");
  (mkTB2_instance->INST_state_set_pw.set_clk_0)("CLK");
  (mkTB2_instance->INST_state_overlap_pw.set_clk_0)("CLK");
  (mkTB2_instance->INST_state_fired_1.set_clk_0)("CLK");
  (mkTB2_instance->set_clk_0)("CLK");
}
void MODEL_mkTB2::destroy_model()
{
  delete mkTB2_instance;
  mkTB2_instance = NULL;
}
void MODEL_mkTB2::reset_model(bool asserted)
{
  (mkTB2_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkTB2::get_instance()
{
  return mkTB2_instance;
}

/* Fill in version numbers */
void MODEL_mkTB2::get_version(char const **name, char const **build)
{
  *name = "2023.07";
  *build = "0eb551dc";
}

/* Get the model creation time */
time_t MODEL_mkTB2::get_creation_time()
{
  
  /* Fri Feb 23 20:28:46 UTC 2024 */
  return 1708720126llu;
}

/* State dumping function */
void MODEL_mkTB2::dump_state()
{
  (mkTB2_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkTB2 & mkTB2_backing(tSimStateHdl simHdl)
{
  static MOD_mkTB2 *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkTB2(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkTB2::dump_VCD_defs()
{
  (mkTB2_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkTB2::dump_VCD(tVCDDumpType dt)
{
  (mkTB2_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkTB2_backing(sim_hdl));
}
