/*
 * Generated by Bluespec Compiler, version 2023.07 (build 0eb551dc)
 * 
 * On Sat Feb 24 16:26:21 CET 2024
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkTB2.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkTB2::MODEL_mkTB2()
{
  mkTB2_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkTB2()
{
  MODEL_mkTB2 *model = new MODEL_mkTB2();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkTB2 &INST_top = *((MOD_mkTB2 *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3_4_A_ETC___d80;
	 tUInt8 DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3_4_A_ETC___d90;
	 tUInt8 DEF_INST_top_DEF_NOT_jj_repeat_count_read__6_BIT_0_7___d78;
	 tUInt8 DEF_INST_top_DEF_counter_6_SLT_8___d97;
	 tUInt8 DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3_4_A_ETC___d116;
	 tUInt8 DEF_INST_top_DEF_NOT_jj_1_repeat_count_read__8_BIT_0_9___d100;
	 tUInt8 DEF_INST_top_DEF_counter_6_SLT_8_7_AND_jj_1_repeat_count_read___ETC___d107;
	 tUInt8 DEF_INST_top_DEF_NOT_counter_6_SLT_8_7___d133;
	 tUInt8 DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3_4_A_ETC___d147;
	 tUInt8 DEF_INST_top_DEF_NOT_jj_2_repeat_count_read__34_BIT_0_35___d136;
	 tUInt8 DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3_4_A_ETC___d105;
	 tUInt8 DEF_INST_top_DEF_abort_whas__0_AND_abort_wget__1_2_OR_state_mkF_ETC___d178;
	 tUInt8 DEF_INST_top_DEF_abort_whas__0_AND_abort_wget__1_2_OR_state_mkF_ETC___d182;
	 tUInt8 DEF_INST_top_DEF_abort_whas__0_AND_abort_wget__1___d32;
	 tUInt8 DEF_INST_top_DEF_NOT_start_wire_whas__3_4_OR_NOT_start_wire_wge_ETC___d37;
	 tUInt8 DEF_INST_top_DEF_abort_whas__0_AND_abort_wget__1_2_OR_state_mkF_ETC___d61;
	 tUInt8 DEF_INST_top_DEF_start_wire_whas__3_AND_start_wire_wget__5___d56;
	 tUInt8 DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3___d54;
	 tUInt8 DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3_4_O_ETC___d82;
	 tUInt8 DEF_INST_top_DEF_NOT_jj_repeat_count_read__6_BIT_0_7_8_AND_NOT__ETC___d91;
	 tUInt8 DEF_INST_top_DEF_jj_repeat_count_read__6_BIT_0_7_AND_NOT_abort__ETC___d86;
	 tUInt8 DEF_INST_top_DEF_counter_6_SLT_8_7_AND_jj_1_repeat_count_read___ETC___d112;
	 tUInt8 DEF_INST_top_DEF_NOT_jj_1_repeat_count_read__8_BIT_0_9_00_AND_N_ETC___d117;
	 tUInt8 DEF_INST_top_DEF_counter_6_SLT_8_7_AND_jj_1_repeat_count_read___ETC___d121;
	 tUInt8 DEF_INST_top_DEF_NOT_counter_6_SLT_8_7_33_AND_jj_2_repeat_count_ETC___d140;
	 tUInt8 DEF_INST_top_DEF_NOT_jj_2_repeat_count_read__34_BIT_0_35_36_AND_ETC___d148;
	 tUInt8 DEF_INST_top_DEF_state_mkFSMstate_read__7_EQ_9___d102;
	 tUInt8 DEF_INST_top_DEF_state_mkFSMstate_read__7_EQ_14___d103;
	 tUInt8 DEF_INST_top_DEF_state_mkFSMstate_read__7_EQ_15___d141;
	 tUInt8 DEF_INST_top_DEF_state_mkFSMstate_read__7_EQ_19___d60;
	 tUInt8 DEF_INST_top_DEF_dut_count_EQ_0___d7;
	 tUInt8 DEF_INST_top_DEF_jj_repeat_count_read__6_BIT_0___d77;
	 tUInt8 DEF_INST_top_DEF_jj_1_repeat_count_read__8_BIT_0___d99;
	 tUInt8 DEF_INST_top_DEF_jj_2_repeat_count_read__34_BIT_0___d135;
	 tUInt8 DEF_INST_top_DEF_abort_wget____d31;
	 tUInt8 DEF_INST_top_DEF_abort_whas____d30;
	 tUInt8 DEF_INST_top_DEF_start_reg__h79305;
	 tUInt8 DEF_INST_top_DEF_running__h79391;
	 tUInt8 DEF_INST_top_DEF_start_wire_wget____d35;
	 tUInt8 DEF_INST_top_DEF_start_wire_whas____d33;
	 tUInt8 DEF_INST_top_DEF_dut_fifo_i_notEmpty____d12;
	 tUInt8 DEF_INST_top_DEF_start_reg_1__h71449;
	 tUInt8 DEF_INST_top_DEF_state_fired__h71451;
	 tUInt8 DEF_INST_top_DEF_x__h782;
	 tUInt8 DEF_INST_top_DEF_state_mkFSMstate_read____d57;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_dut_cc;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_dut_cc;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_dut_r1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_dut_r1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_dut_r2;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_dut_r2;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_dut_r3;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_dut_r3;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_dut_r4;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_dut_r4;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_start_reg__dreg_update;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_start_reg__dreg_update;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_state_handle_abort;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_state_handle_abort;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_state_fired__dreg_update;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_state_fired__dreg_update;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_state_every;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_state_every;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_restart;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_restart;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l87c13;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l88c13;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l95c16;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l96c13;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l102c13;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l102c25;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_f_init_l109c13;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l110c17;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l110c29;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_f_update_l109c13;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l121c13;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l121c25;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l129c13;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l102c13;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_action_ovlp_r_update_l102c13;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l110c17;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_action_ovlp_r_update_l110c17;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l121c13;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_action_ovlp_r_update_l121c13;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_idle_l86c18;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_idle_l86c18;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_fsm_start;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_fsm_start;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_auto_start;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_auto_start;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_auto_finish;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_auto_finish;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_10;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_10;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_11;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_12;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_12;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_13;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_13;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_14;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_14;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_15;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_15;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_16;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_16;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_17;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_17;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_18;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_18;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_19;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_19;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_20;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_20;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_21;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_21;
	 INST_top.DEF_jj_repeat_count_read____d76 = INST_top.INST_jj_repeat_count.METH_read();
	 DEF_INST_top_DEF_state_mkFSMstate_read____d57 = INST_top.INST_state_mkFSMstate.METH_read();
	 DEF_INST_top_DEF_abort_whas____d30 = INST_top.INST_abort.METH_whas();
	 DEF_INST_top_DEF_abort_wget____d31 = INST_top.INST_abort.METH_wget();
	 DEF_INST_top_DEF_jj_repeat_count_read__6_BIT_0___d77 = (tUInt8)((tUInt8)1u & (INST_top.DEF_jj_repeat_count_read____d76));
	 DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3___d54 = !DEF_INST_top_DEF_abort_whas____d30 || !DEF_INST_top_DEF_abort_wget____d31;
	 DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3_4_A_ETC___d90 = DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3___d54 && DEF_INST_top_DEF_state_mkFSMstate_read____d57 == (tUInt8)7u;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_f_init_l109c13 = DEF_INST_top_DEF_jj_repeat_count_read__6_BIT_0___d77 && DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3_4_A_ETC___d90;
	 INST_top.DEF_WILL_FIRE_RL_action_f_init_l109c13 = DEF_INST_top_DEF_CAN_FIRE_RL_action_f_init_l109c13;
	 INST_top.DEF_jj_1_repeat_count_read____d98 = INST_top.INST_jj_1_repeat_count.METH_read();
	 DEF_INST_top_DEF_jj_1_repeat_count_read__8_BIT_0___d99 = (tUInt8)((tUInt8)1u & (INST_top.DEF_jj_1_repeat_count_read____d98));
	 DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3_4_A_ETC___d116 = DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3___d54 && DEF_INST_top_DEF_state_mkFSMstate_read____d57 == (tUInt8)12u;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_f_update_l109c13 = DEF_INST_top_DEF_jj_1_repeat_count_read__8_BIT_0___d99 && DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3_4_A_ETC___d116;
	 INST_top.DEF_WILL_FIRE_RL_action_f_update_l109c13 = DEF_INST_top_DEF_CAN_FIRE_RL_action_f_update_l109c13;
	 INST_top.DEF_jj_2_repeat_count_read____d134 = INST_top.INST_jj_2_repeat_count.METH_read();
	 DEF_INST_top_DEF_jj_2_repeat_count_read__34_BIT_0___d135 = (tUInt8)((tUInt8)1u & (INST_top.DEF_jj_2_repeat_count_read____d134));
	 DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3_4_A_ETC___d147 = DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3___d54 && DEF_INST_top_DEF_state_mkFSMstate_read____d57 == (tUInt8)17u;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l129c13 = DEF_INST_top_DEF_jj_2_repeat_count_read__34_BIT_0___d135 && DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3_4_A_ETC___d147;
	 INST_top.DEF_WILL_FIRE_RL_action_l129c13 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l129c13;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l88c13 = DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3___d54 && DEF_INST_top_DEF_state_mkFSMstate_read____d57 == (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_action_l88c13 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l88c13;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l95c16 = INST_top.INST_dut_fifo.METH_i_notFull() && (DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3___d54 && DEF_INST_top_DEF_state_mkFSMstate_read____d57 == (tUInt8)2u);
	 INST_top.DEF_WILL_FIRE_RL_action_l95c16 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l95c16;
	 INST_top.DEF_dut_bbit__h77840 = INST_top.INST_dut_bbit.METH_read();
	 INST_top.DEF_NOT_dut_bbit_5___d66 = !(INST_top.DEF_dut_bbit__h77840);
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l96c13 = INST_top.DEF_NOT_dut_bbit_5___d66 && (DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3___d54 && DEF_INST_top_DEF_state_mkFSMstate_read____d57 == (tUInt8)3u);
	 INST_top.DEF_WILL_FIRE_RL_action_l96c13 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l96c13;
	 INST_top.DEF_state_can_overlap__h7145 = INST_top.INST_state_can_overlap.METH_read();
	 DEF_INST_top_DEF_NOT_jj_repeat_count_read__6_BIT_0_7___d78 = !DEF_INST_top_DEF_jj_repeat_count_read__6_BIT_0___d77;
	 DEF_INST_top_DEF_NOT_jj_repeat_count_read__6_BIT_0_7_8_AND_NOT__ETC___d91 = DEF_INST_top_DEF_NOT_jj_repeat_count_read__6_BIT_0_7___d78 && DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3_4_A_ETC___d90;
	 DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3_4_A_ETC___d80 = DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3___d54 && DEF_INST_top_DEF_state_mkFSMstate_read____d57 == (tUInt8)4u;
	 DEF_INST_top_DEF_jj_repeat_count_read__6_BIT_0_7_AND_NOT_abort__ETC___d86 = (DEF_INST_top_DEF_jj_repeat_count_read__6_BIT_0___d77 && DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3_4_A_ETC___d80) || (DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3___d54 && DEF_INST_top_DEF_state_mkFSMstate_read____d57 == (tUInt8)5u);
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l102c13 = INST_top.DEF_state_can_overlap__h7145 && (DEF_INST_top_DEF_jj_repeat_count_read__6_BIT_0_7_AND_NOT_abort__ETC___d86 || DEF_INST_top_DEF_NOT_jj_repeat_count_read__6_BIT_0_7_8_AND_NOT__ETC___d91);
	 DEF_INST_top_DEF_WILL_FIRE_RL_action_ovlp_r_update_l102c13 = DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l102c13;
	 INST_top.DEF_x__h75742 = INST_top.INST_counter.METH_read();
	 DEF_INST_top_DEF_state_mkFSMstate_read__7_EQ_14___d103 = DEF_INST_top_DEF_state_mkFSMstate_read____d57 == (tUInt8)14u;
	 DEF_INST_top_DEF_state_mkFSMstate_read__7_EQ_9___d102 = DEF_INST_top_DEF_state_mkFSMstate_read____d57 == (tUInt8)9u;
	 DEF_INST_top_DEF_NOT_jj_1_repeat_count_read__8_BIT_0_9___d100 = !DEF_INST_top_DEF_jj_1_repeat_count_read__8_BIT_0___d99;
	 DEF_INST_top_DEF_NOT_jj_1_repeat_count_read__8_BIT_0_9_00_AND_N_ETC___d117 = DEF_INST_top_DEF_NOT_jj_1_repeat_count_read__8_BIT_0_9___d100 && DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3_4_A_ETC___d116;
	 DEF_INST_top_DEF_counter_6_SLT_8___d97 = primSLT8(1u,
							   32u,
							   (tUInt32)(INST_top.DEF_x__h75742),
							   32u,
							   8u);
	 DEF_INST_top_DEF_counter_6_SLT_8_7_AND_jj_1_repeat_count_read___ETC___d107 = DEF_INST_top_DEF_counter_6_SLT_8___d97 && DEF_INST_top_DEF_jj_1_repeat_count_read__8_BIT_0___d99;
	 DEF_INST_top_DEF_counter_6_SLT_8_7_AND_jj_1_repeat_count_read___ETC___d121 = DEF_INST_top_DEF_counter_6_SLT_8_7_AND_jj_1_repeat_count_read___ETC___d107 && (DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3___d54 && DEF_INST_top_DEF_state_mkFSMstate_read__7_EQ_14___d103);
	 DEF_INST_top_DEF_counter_6_SLT_8_7_AND_jj_1_repeat_count_read___ETC___d112 = (DEF_INST_top_DEF_counter_6_SLT_8_7_AND_jj_1_repeat_count_read___ETC___d107 && (DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3___d54 && DEF_INST_top_DEF_state_mkFSMstate_read__7_EQ_9___d102)) || (DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3___d54 && DEF_INST_top_DEF_state_mkFSMstate_read____d57 == (tUInt8)10u);
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l110c17 = INST_top.DEF_state_can_overlap__h7145 && (DEF_INST_top_DEF_counter_6_SLT_8_7_AND_jj_1_repeat_count_read___ETC___d112 || (DEF_INST_top_DEF_NOT_jj_1_repeat_count_read__8_BIT_0_9_00_AND_N_ETC___d117 || DEF_INST_top_DEF_counter_6_SLT_8_7_AND_jj_1_repeat_count_read___ETC___d121));
	 DEF_INST_top_DEF_WILL_FIRE_RL_action_ovlp_r_update_l110c17 = DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l110c17;
	 DEF_INST_top_DEF_state_mkFSMstate_read__7_EQ_15___d141 = DEF_INST_top_DEF_state_mkFSMstate_read____d57 == (tUInt8)15u;
	 DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3_4_A_ETC___d105 = DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3___d54 && (DEF_INST_top_DEF_state_mkFSMstate_read__7_EQ_9___d102 || DEF_INST_top_DEF_state_mkFSMstate_read__7_EQ_14___d103);
	 DEF_INST_top_DEF_NOT_jj_2_repeat_count_read__34_BIT_0_35___d136 = !DEF_INST_top_DEF_jj_2_repeat_count_read__34_BIT_0___d135;
	 DEF_INST_top_DEF_NOT_jj_2_repeat_count_read__34_BIT_0_35_36_AND_ETC___d148 = DEF_INST_top_DEF_NOT_jj_2_repeat_count_read__34_BIT_0_35___d136 && DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3_4_A_ETC___d147;
	 DEF_INST_top_DEF_NOT_counter_6_SLT_8_7___d133 = !DEF_INST_top_DEF_counter_6_SLT_8___d97;
	 DEF_INST_top_DEF_NOT_counter_6_SLT_8_7_33_AND_jj_2_repeat_count_ETC___d140 = (DEF_INST_top_DEF_NOT_counter_6_SLT_8_7___d133 && DEF_INST_top_DEF_jj_2_repeat_count_read__34_BIT_0___d135) && DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3_4_A_ETC___d105;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l121c13 = INST_top.DEF_state_can_overlap__h7145 && (DEF_INST_top_DEF_NOT_counter_6_SLT_8_7_33_AND_jj_2_repeat_count_ETC___d140 || ((DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3___d54 && DEF_INST_top_DEF_state_mkFSMstate_read__7_EQ_15___d141) || DEF_INST_top_DEF_NOT_jj_2_repeat_count_read__34_BIT_0_35_36_AND_ETC___d148));
	 DEF_INST_top_DEF_WILL_FIRE_RL_action_ovlp_r_update_l121c13 = DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l121c13;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l102c13 = DEF_INST_top_DEF_NOT_jj_repeat_count_read__6_BIT_0_7___d78 && DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3_4_A_ETC___d80;
	 INST_top.DEF_WILL_FIRE_RL_action_r_init_l102c13 = DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l102c13;
	 DEF_INST_top_DEF_state_fired__h71451 = INST_top.INST_state_fired.METH_read();
	 DEF_INST_top_DEF_start_reg_1__h71449 = INST_top.INST_start_reg_1.METH_read();
	 DEF_INST_top_DEF_running__h79391 = INST_top.INST_running.METH_read();
	 DEF_INST_top_DEF_start_reg__h79305 = INST_top.INST_start_reg.METH_read();
	 DEF_INST_top_DEF_state_mkFSMstate_read__7_EQ_19___d60 = DEF_INST_top_DEF_state_mkFSMstate_read____d57 == (tUInt8)19u;
	 DEF_INST_top_DEF_abort_whas__0_AND_abort_wget__1___d32 = DEF_INST_top_DEF_abort_whas____d30 && DEF_INST_top_DEF_abort_wget____d31;
	 DEF_INST_top_DEF_abort_whas__0_AND_abort_wget__1_2_OR_state_mkF_ETC___d61 = (DEF_INST_top_DEF_abort_whas__0_AND_abort_wget__1___d32 || DEF_INST_top_DEF_state_mkFSMstate_read____d57 == (tUInt8)0u) || DEF_INST_top_DEF_state_mkFSMstate_read__7_EQ_19___d60;
	 DEF_INST_top_DEF_abort_whas__0_AND_abort_wget__1_2_OR_state_mkF_ETC___d178 = DEF_INST_top_DEF_abort_whas__0_AND_abort_wget__1_2_OR_state_mkF_ETC___d61 && (!DEF_INST_top_DEF_start_reg_1__h71449 || DEF_INST_top_DEF_state_fired__h71451);
	 DEF_INST_top_DEF_abort_whas__0_AND_abort_wget__1_2_OR_state_mkF_ETC___d182 = DEF_INST_top_DEF_abort_whas__0_AND_abort_wget__1_2_OR_state_mkF_ETC___d178 && !DEF_INST_top_DEF_start_reg__h79305;
	 DEF_INST_top_DEF_CAN_FIRE_RL_auto_finish = DEF_INST_top_DEF_running__h79391 && DEF_INST_top_DEF_abort_whas__0_AND_abort_wget__1_2_OR_state_mkF_ETC___d182;
	 DEF_INST_top_DEF_WILL_FIRE_RL_auto_finish = DEF_INST_top_DEF_CAN_FIRE_RL_auto_finish;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l110c17 = (DEF_INST_top_DEF_counter_6_SLT_8___d97 && DEF_INST_top_DEF_NOT_jj_1_repeat_count_read__8_BIT_0_9___d100) && DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3_4_A_ETC___d105;
	 INST_top.DEF_WILL_FIRE_RL_action_r_init_l110c17 = DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l110c17;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l121c13 = (DEF_INST_top_DEF_NOT_counter_6_SLT_8_7___d133 && DEF_INST_top_DEF_NOT_jj_2_repeat_count_read__34_BIT_0_35___d136) && DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3_4_A_ETC___d105;
	 INST_top.DEF_WILL_FIRE_RL_action_r_init_l121c13 = DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l121c13;
	 DEF_INST_top_DEF_CAN_FIRE_RL_auto_start = DEF_INST_top_DEF_abort_whas__0_AND_abort_wget__1_2_OR_state_mkF_ETC___d182 && !DEF_INST_top_DEF_running__h79391;
	 DEF_INST_top_DEF_WILL_FIRE_RL_auto_start = DEF_INST_top_DEF_CAN_FIRE_RL_auto_start;
	 INST_top.DEF_b__h322 = INST_top.INST_dut_count.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_dut_cc = !primSLE8(1u, 32u, (tUInt32)(INST_top.DEF_b__h322), 32u, 0u);
	 DEF_INST_top_DEF_WILL_FIRE_RL_dut_cc = DEF_INST_top_DEF_CAN_FIRE_RL_dut_cc;
	 DEF_INST_top_DEF_x__h782 = INST_top.INST_dut_state.METH_read();
	 DEF_INST_top_DEF_dut_count_EQ_0___d7 = (INST_top.DEF_b__h322) == 0u;
	 DEF_INST_top_DEF_CAN_FIRE_RL_dut_r1 = DEF_INST_top_DEF_x__h782 == (tUInt8)0u && DEF_INST_top_DEF_dut_count_EQ_0___d7;
	 DEF_INST_top_DEF_WILL_FIRE_RL_dut_r1 = DEF_INST_top_DEF_CAN_FIRE_RL_dut_r1;
	 DEF_INST_top_DEF_CAN_FIRE_RL_dut_r2 = DEF_INST_top_DEF_x__h782 == (tUInt8)1u && DEF_INST_top_DEF_dut_count_EQ_0___d7;
	 DEF_INST_top_DEF_WILL_FIRE_RL_dut_r2 = DEF_INST_top_DEF_CAN_FIRE_RL_dut_r2;
	 DEF_INST_top_DEF_dut_fifo_i_notEmpty____d12 = INST_top.INST_dut_fifo.METH_i_notEmpty();
	 DEF_INST_top_DEF_CAN_FIRE_RL_dut_r3 = DEF_INST_top_DEF_dut_fifo_i_notEmpty____d12 && (DEF_INST_top_DEF_x__h782 == (tUInt8)2u && DEF_INST_top_DEF_dut_count_EQ_0___d7);
	 DEF_INST_top_DEF_WILL_FIRE_RL_dut_r3 = DEF_INST_top_DEF_CAN_FIRE_RL_dut_r3;
	 DEF_INST_top_DEF_CAN_FIRE_RL_dut_r4 = DEF_INST_top_DEF_dut_fifo_i_notEmpty____d12 && (DEF_INST_top_DEF_x__h782 == (tUInt8)3u && DEF_INST_top_DEF_dut_count_EQ_0___d7);
	 DEF_INST_top_DEF_WILL_FIRE_RL_dut_r4 = DEF_INST_top_DEF_CAN_FIRE_RL_dut_r4;
	 DEF_INST_top_DEF_CAN_FIRE_RL_fsm_start = DEF_INST_top_DEF_abort_whas__0_AND_abort_wget__1_2_OR_state_mkF_ETC___d178 && DEF_INST_top_DEF_start_reg__h79305;
	 DEF_INST_top_DEF_WILL_FIRE_RL_fsm_start = DEF_INST_top_DEF_CAN_FIRE_RL_fsm_start;
	 DEF_INST_top_DEF_CAN_FIRE_RL_restart = (DEF_INST_top_DEF_start_reg_1__h71449 && !DEF_INST_top_DEF_state_fired__h71451) && DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3___d54;
	 DEF_INST_top_DEF_WILL_FIRE_RL_restart = DEF_INST_top_DEF_CAN_FIRE_RL_restart;
	 DEF_INST_top_DEF_CAN_FIRE_RL_start_reg__dreg_update = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_start_reg__dreg_update = DEF_INST_top_DEF_CAN_FIRE_RL_start_reg__dreg_update;
	 DEF_INST_top_DEF_CAN_FIRE_RL_state_every = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_state_every = DEF_INST_top_DEF_CAN_FIRE_RL_state_every;
	 DEF_INST_top_DEF_CAN_FIRE_RL_state_fired__dreg_update = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_state_fired__dreg_update = DEF_INST_top_DEF_CAN_FIRE_RL_state_fired__dreg_update;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_10 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_10 = DEF_INST_top_DEF_CAN_FIRE___me_check_10;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_11 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_11 = DEF_INST_top_DEF_CAN_FIRE___me_check_11;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_12 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_12 = DEF_INST_top_DEF_CAN_FIRE___me_check_12;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_13 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_13 = DEF_INST_top_DEF_CAN_FIRE___me_check_13;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_14 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_14 = DEF_INST_top_DEF_CAN_FIRE___me_check_14;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_15 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_15 = DEF_INST_top_DEF_CAN_FIRE___me_check_15;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_16 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_16 = DEF_INST_top_DEF_CAN_FIRE___me_check_16;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_17 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_17 = DEF_INST_top_DEF_CAN_FIRE___me_check_17;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_18 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_18 = DEF_INST_top_DEF_CAN_FIRE___me_check_18;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_19 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_19 = DEF_INST_top_DEF_CAN_FIRE___me_check_19;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_20 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_20 = DEF_INST_top_DEF_CAN_FIRE___me_check_20;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_21 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_21 = DEF_INST_top_DEF_CAN_FIRE___me_check_21;
	 if (INST_top.DEF_WILL_FIRE_RL_action_f_init_l109c13)
	   INST_top.RL_action_f_init_l109c13();
	 if (INST_top.DEF_WILL_FIRE_RL_action_f_update_l109c13)
	   INST_top.RL_action_f_update_l109c13();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l129c13)
	   INST_top.RL_action_l129c13();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l88c13)
	   INST_top.RL_action_l88c13();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l96c13)
	   INST_top.RL_action_l96c13();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_action_ovlp_r_update_l102c13)
	   INST_top.RL_action_ovlp_r_update_l102c13();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_action_ovlp_r_update_l110c17)
	   INST_top.RL_action_ovlp_r_update_l110c17();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_action_ovlp_r_update_l121c13)
	   INST_top.RL_action_ovlp_r_update_l121c13();
	 if (INST_top.DEF_WILL_FIRE_RL_action_r_init_l102c13)
	   INST_top.RL_action_r_init_l102c13();
	 if (INST_top.DEF_WILL_FIRE_RL_action_r_init_l110c17)
	   INST_top.RL_action_r_init_l110c17();
	 if (INST_top.DEF_WILL_FIRE_RL_action_r_init_l121c13)
	   INST_top.RL_action_r_init_l121c13();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_auto_start)
	   INST_top.RL_auto_start();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_dut_cc)
	   INST_top.RL_dut_cc();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_fsm_start)
	   INST_top.RL_fsm_start();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_restart)
	   INST_top.RL_restart();
	 DEF_INST_top_DEF_start_wire_whas____d33 = INST_top.INST_start_wire.METH_whas();
	 DEF_INST_top_DEF_start_wire_wget____d35 = INST_top.INST_start_wire.METH_wget();
	 DEF_INST_top_DEF_start_wire_whas__3_AND_start_wire_wget__5___d56 = DEF_INST_top_DEF_start_wire_whas____d33 && DEF_INST_top_DEF_start_wire_wget____d35;
	 DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3_4_O_ETC___d82 = DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3___d54 || DEF_INST_top_DEF_start_wire_whas__3_AND_start_wire_wget__5___d56;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l102c25 = (DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3_4_O_ETC___d82 && (DEF_INST_top_DEF_jj_repeat_count_read__6_BIT_0_7_AND_NOT_abort__ETC___d86 || ((DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3___d54 && DEF_INST_top_DEF_state_mkFSMstate_read____d57 == (tUInt8)6u) || DEF_INST_top_DEF_NOT_jj_repeat_count_read__6_BIT_0_7_8_AND_NOT__ETC___d91))) && !((((DEF_INST_top_DEF_CAN_FIRE_RL_auto_start || DEF_INST_top_DEF_CAN_FIRE_RL_fsm_start) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l121c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l110c17)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_l129c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l121c13) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_f_update_l109c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l110c17))) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_f_init_l109c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l102c13) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l96c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l88c13)));
	 INST_top.DEF_WILL_FIRE_RL_action_l102c25 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l102c25;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l110c29 = (DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3_4_O_ETC___d82 && ((DEF_INST_top_DEF_counter_6_SLT_8_7_AND_jj_1_repeat_count_read___ETC___d112 || ((DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3___d54 && DEF_INST_top_DEF_state_mkFSMstate_read____d57 == (tUInt8)11u) || DEF_INST_top_DEF_NOT_jj_1_repeat_count_read__8_BIT_0_9_00_AND_N_ETC___d117)) || DEF_INST_top_DEF_counter_6_SLT_8_7_AND_jj_1_repeat_count_read___ETC___d121)) && !((((DEF_INST_top_DEF_CAN_FIRE_RL_auto_start || DEF_INST_top_DEF_CAN_FIRE_RL_fsm_start) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l121c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l102c13)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_l129c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l121c13) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_f_update_l109c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l110c17))) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_f_init_l109c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l102c13) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l96c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l88c13)));
	 INST_top.DEF_WILL_FIRE_RL_action_l110c29 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l110c29;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l121c25 = (DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3_4_O_ETC___d82 && ((DEF_INST_top_DEF_NOT_counter_6_SLT_8_7_33_AND_jj_2_repeat_count_ETC___d140 || (DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3___d54 && (DEF_INST_top_DEF_state_mkFSMstate_read__7_EQ_15___d141 || DEF_INST_top_DEF_state_mkFSMstate_read____d57 == (tUInt8)16u))) || DEF_INST_top_DEF_NOT_jj_2_repeat_count_read__34_BIT_0_35_36_AND_ETC___d148)) && !((((DEF_INST_top_DEF_CAN_FIRE_RL_auto_start || DEF_INST_top_DEF_CAN_FIRE_RL_fsm_start) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l110c17 || DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l102c13)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_l129c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l121c13) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_f_update_l109c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l110c17))) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_f_init_l109c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l102c13) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l96c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l88c13)));
	 INST_top.DEF_WILL_FIRE_RL_action_l121c25 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l121c25;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l87c13 = (DEF_INST_top_DEF_start_wire_whas__3_AND_start_wire_wget__5___d56 && DEF_INST_top_DEF_abort_whas__0_AND_abort_wget__1_2_OR_state_mkF_ETC___d61) && !((((DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l121c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l110c17) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l102c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l129c13)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l121c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_f_update_l109c13) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l110c17 || DEF_INST_top_DEF_CAN_FIRE_RL_action_f_init_l109c13))) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l102c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l96c13) || DEF_INST_top_DEF_CAN_FIRE_RL_action_l88c13));
	 INST_top.DEF_WILL_FIRE_RL_action_l87c13 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l87c13;
	 DEF_INST_top_DEF_NOT_start_wire_whas__3_4_OR_NOT_start_wire_wge_ETC___d37 = !DEF_INST_top_DEF_start_wire_whas____d33 || !DEF_INST_top_DEF_start_wire_wget____d35;
	 DEF_INST_top_DEF_CAN_FIRE_RL_state_handle_abort = (DEF_INST_top_DEF_abort_whas__0_AND_abort_wget__1___d32 && DEF_INST_top_DEF_NOT_start_wire_whas__3_4_OR_NOT_start_wire_wge_ETC___d37) && !((((DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l121c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l110c17) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l102c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l129c13)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l121c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_f_update_l109c13) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l110c17 || DEF_INST_top_DEF_CAN_FIRE_RL_action_f_init_l109c13))) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l102c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l96c13) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l88c13 || DEF_INST_top_DEF_CAN_FIRE_RL_restart)));
	 DEF_INST_top_DEF_WILL_FIRE_RL_state_handle_abort = DEF_INST_top_DEF_CAN_FIRE_RL_state_handle_abort;
	 DEF_INST_top_DEF_CAN_FIRE_RL_idle_l86c18 = (DEF_INST_top_DEF_NOT_start_wire_whas__3_4_OR_NOT_start_wire_wge_ETC___d37 && (DEF_INST_top_DEF_NOT_abort_whas__0_2_OR_NOT_abort_wget__1_3___d54 && DEF_INST_top_DEF_state_mkFSMstate_read__7_EQ_19___d60)) && !((((DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l121c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l110c17) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_ovlp_r_update_l102c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l129c13)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l121c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_f_update_l109c13) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l110c17 || DEF_INST_top_DEF_CAN_FIRE_RL_action_f_init_l109c13))) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_r_init_l102c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l96c13) || DEF_INST_top_DEF_CAN_FIRE_RL_action_l88c13));
	 DEF_INST_top_DEF_WILL_FIRE_RL_idle_l86c18 = DEF_INST_top_DEF_CAN_FIRE_RL_idle_l86c18;
	 if (INST_top.DEF_WILL_FIRE_RL_action_l102c25)
	   INST_top.RL_action_l102c25();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l121c25)
	   INST_top.RL_action_l121c25();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l110c29)
	   INST_top.RL_action_l110c29();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l87c13)
	   INST_top.RL_action_l87c13();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_auto_finish)
	   INST_top.RL_auto_finish();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_dut_r1)
	   INST_top.RL_dut_r1();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l95c16)
	   INST_top.RL_action_l95c16();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_dut_r3)
	   INST_top.RL_dut_r3();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_start_reg__dreg_update)
	   INST_top.RL_start_reg__dreg_update();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_dut_r4)
	   INST_top.RL_dut_r4();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_state_handle_abort)
	   INST_top.RL_state_handle_abort();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_10)
	   INST_top.__me_check_10();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_11)
	   INST_top.__me_check_11();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_12)
	   INST_top.__me_check_12();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_dut_r2)
	   INST_top.RL_dut_r2();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_13)
	   INST_top.__me_check_13();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_14)
	   INST_top.__me_check_14();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_15)
	   INST_top.__me_check_15();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_16)
	   INST_top.__me_check_16();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_17)
	   INST_top.__me_check_17();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_18)
	   INST_top.__me_check_18();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_20)
	   INST_top.__me_check_20();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_19)
	   INST_top.__me_check_19();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_21)
	   INST_top.__me_check_21();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_idle_l86c18)
	   INST_top.RL_idle_l86c18();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_state_every)
	   INST_top.RL_state_every();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_state_fired__dreg_update)
	   INST_top.RL_state_fired__dreg_update();
	 INST_top.INST_state_fired_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_state_overlap_pw.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_state_set_pw.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_abort.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_start_reg_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_start_wire.clk((tUInt8)1u, (tUInt8)1u);
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_dut_fifo.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_dut_bbit.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut_state.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut_count.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut_c.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_counter.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mistakes.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_start_reg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_start_reg_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_jj_repeat_count.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_jj_1_repeat_count.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_jj_2_repeat_count.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_state_mkFSMstate.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_state_fired.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_state_can_overlap.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_running.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkTB2::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkTB2_instance = new MOD_mkTB2(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkTB2_instance->INST_dut_fifo.set_clk_0)("CLK");
  (mkTB2_instance->INST_start_wire.set_clk_0)("CLK");
  (mkTB2_instance->INST_start_reg_2.set_clk_0)("CLK");
  (mkTB2_instance->INST_abort.set_clk_0)("CLK");
  (mkTB2_instance->INST_state_set_pw.set_clk_0)("CLK");
  (mkTB2_instance->INST_state_overlap_pw.set_clk_0)("CLK");
  (mkTB2_instance->INST_state_fired_1.set_clk_0)("CLK");
  (mkTB2_instance->set_clk_0)("CLK");
}
void MODEL_mkTB2::destroy_model()
{
  delete mkTB2_instance;
  mkTB2_instance = NULL;
}
void MODEL_mkTB2::reset_model(bool asserted)
{
  (mkTB2_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkTB2::get_instance()
{
  return mkTB2_instance;
}

/* Fill in version numbers */
void MODEL_mkTB2::get_version(char const **name, char const **build)
{
  *name = "2023.07";
  *build = "0eb551dc";
}

/* Get the model creation time */
time_t MODEL_mkTB2::get_creation_time()
{
  
  /* Sat Feb 24 15:26:21 UTC 2024 */
  return 1708788381llu;
}

/* State dumping function */
void MODEL_mkTB2::dump_state()
{
  (mkTB2_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkTB2 & mkTB2_backing(tSimStateHdl simHdl)
{
  static MOD_mkTB2 *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkTB2(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkTB2::dump_VCD_defs()
{
  (mkTB2_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkTB2::dump_VCD(tVCDDumpType dt)
{
  (mkTB2_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkTB2_backing(sim_hdl));
}
