/*
 * Generated by Bluespec Compiler, version 2023.07 (build 0eb551dc)
 * 
 * On Tue Jan  9 17:36:38 CET 2024
 * 
 */

/* Generation options: */
#ifndef __mkFoo_h__
#define __mkFoo_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkFoo module */
class MOD_mkFoo : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt32> INST_cycle;
  MOD_Reg<tUInt32> INST_x;
  MOD_Reg<tUInt32> INST_y;
 
 /* Constructor */
 public:
  MOD_mkFoo(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUInt8 PORT_EN_avx;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_avx;
 
 /* Local definitions */
 private:
  tUInt32 DEF_signed_cycle___d7;
  tUInt32 DEF_b__h184;
  tUInt32 DEF_b__h242;
  tUInt32 DEF_b__h293;
 
 /* Rules */
 public:
  void RL_count_cycles();
  void RL_incx();
  void RL_incy();
 
 /* Methods */
 public:
  tUInt32 METH_avx();
  tUInt8 METH_RDY_avx();
  tUInt32 METH_vy();
  tUInt8 METH_RDY_vy();
  void METH_ay();
  tUInt8 METH_RDY_ay();
  tUInt32 METH_get_cycle_count();
  tUInt8 METH_RDY_get_cycle_count();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkFoo &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkFoo &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkFoo &backing);
};

#endif /* ifndef __mkFoo_h__ */
