/*
 * Generated by Bluespec Compiler, version 2023.07 (build 0eb551dc)
 * 
 * On Wed Dec 27 16:32:05 CET 2023
 * 
 */
#include "bluesim_primitives.h"
#include "mkDut.h"


/* Constructor */
MOD_mkDut::MOD_mkDut(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_x(simHdl, "x", this, 32u, 0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u)
{
  symbol_count = 3u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkDut::init_symbols_0()
{
  init_symbol(&symbols[0u], "RL_count", SYM_RULE);
  init_symbol(&symbols[1u], "x", SYM_MODULE, &INST_x);
  init_symbol(&symbols[2u], "x__h122", SYM_DEF, &DEF_x__h122, 32u);
}


/* Rule actions */

void MOD_mkDut::RL_count()
{
  tUInt32 DEF_x_PLUS_1___d2;
  DEF_x__h122 = INST_x.METH_read();
  DEF_x_PLUS_1___d2 = DEF_x__h122 + 1u;
  INST_x.METH_write(DEF_x_PLUS_1___d2);
}


/* Methods */

tUInt32 MOD_mkDut::METH_f1()
{
  tUInt32 PORT_f1;
  DEF_x__h122 = INST_x.METH_read();
  PORT_f1 = DEF_x__h122;
  return PORT_f1;
}

tUInt8 MOD_mkDut::METH_RDY_f1()
{
  tUInt8 DEF_CAN_FIRE_f1;
  tUInt8 PORT_RDY_f1;
  DEF_CAN_FIRE_f1 = (tUInt8)1u;
  PORT_RDY_f1 = DEF_CAN_FIRE_f1;
  return PORT_RDY_f1;
}

tUInt32 MOD_mkDut::METH_f2()
{
  tUInt32 PORT_f2;
  DEF_x__h122 = INST_x.METH_read();
  PORT_f2 = DEF_x__h122;
  return PORT_f2;
}

tUInt8 MOD_mkDut::METH_RDY_f2()
{
  tUInt8 DEF_CAN_FIRE_f2;
  tUInt8 DEF_x_BIT_0___h123;
  tUInt8 PORT_RDY_f2;
  DEF_x__h122 = INST_x.METH_read();
  DEF_x_BIT_0___h123 = (tUInt8)((tUInt8)1u & DEF_x__h122);
  DEF_CAN_FIRE_f2 = !DEF_x_BIT_0___h123;
  PORT_RDY_f2 = DEF_CAN_FIRE_f2;
  return PORT_RDY_f2;
}


/* Reset routines */

void MOD_mkDut::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_x.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkDut::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkDut::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_x.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkDut::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 3u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h122", 32u);
  num = INST_x.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkDut::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkDut &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkDut::vcd_defs(tVCDDumpType dt, MOD_mkDut &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_x__h122) != DEF_x__h122)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h122, 32u);
	backing.DEF_x__h122 = DEF_x__h122;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_x__h122, 32u);
      backing.DEF_x__h122 = DEF_x__h122;
    }
}

void MOD_mkDut::vcd_prims(tVCDDumpType dt, MOD_mkDut &backing)
{
  INST_x.dump_VCD(dt, backing.INST_x);
}
