/*
 * Generated by Bluespec Compiler, version 2023.07 (build 0eb551dc)
 * 
 * On Mon Jan 15 17:07:25 CET 2024
 * 
 */

/* Generation options: */
#ifndef __mkHelloBluespec_h__
#define __mkHelloBluespec_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkHelloBluespec module */
class MOD_mkHelloBluespec : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt32> INST_counter;
  MOD_Reg<tUInt8> INST_ledStatus;
 
 /* Constructor */
 public:
  MOD_mkHelloBluespec(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_counter_EQ_0x1FFFFFF___d2;
  tUInt32 DEF_b__h109;
 
 /* Local definitions */
 private:
  tUInt64 DEF_v__h153;
  tUInt8 DEF_ledStatus__h193;
 
 /* Rules */
 public:
  void RL_count();
  void RL_hellodisplay();
 
 /* Methods */
 public:
  tUInt8 METH_led();
  tUInt8 METH_RDY_led();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkHelloBluespec &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkHelloBluespec &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkHelloBluespec &backing);
};

#endif /* ifndef __mkHelloBluespec_h__ */
