/*
 * Generated by Bluespec Compiler, version 2023.07 (build 0eb551dc)
 * 
 * On Mon Jan  8 20:34:35 CET 2024
 * 
 */
extern "C" {
  unsigned long long readImage_create(char *);
  void readImage_delete(unsigned long long );
  char readImage_getPixelAt(unsigned long long , unsigned int );
  unsigned long long writeImage_create(char *, unsigned int , unsigned int , unsigned int );
  void writeImage_delete(unsigned long long );
  void writeImage_putPixel(unsigned long long , char );
}
