/*
 * Generated by Bluespec Compiler, version 2023.07 (build 0eb551dc)
 * 
 * On Wed Feb 14 18:26:12 CET 2024
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkTB1.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkTB1::MODEL_mkTB1()
{
  mkTB1_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkTB1()
{
  MODEL_mkTB1 *model = new MODEL_mkTB1();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkTB1 &INST_top = *((MOD_mkTB1 *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_dut_switch;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_dut_switch;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_dut_r1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_dut_r1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r1;
	 DEF_INST_top_DEF_CAN_FIRE_RL_dut_r1 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_dut_r1 = DEF_INST_top_DEF_CAN_FIRE_RL_dut_r1;
	 DEF_INST_top_DEF_CAN_FIRE_RL_dut_switch = INST_top.INST_dut_queue.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_dut_switch = DEF_INST_top_DEF_CAN_FIRE_RL_dut_switch;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r = INST_top.INST_dut_queue.METH_i_notEmpty();
	 DEF_INST_top_DEF_WILL_FIRE_RL_r = DEF_INST_top_DEF_CAN_FIRE_RL_r;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r1 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r1 = DEF_INST_top_DEF_CAN_FIRE_RL_r1;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_dut_switch)
	   INST_top.RL_dut_switch();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_dut_r1)
	   INST_top.RL_dut_r1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r)
	   INST_top.RL_r();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r1)
	   INST_top.RL_r1();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_dut_queue.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_dut_cntr.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_cntr.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkTB1::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkTB1_instance = new MOD_mkTB1(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkTB1_instance->INST_dut_queue.set_clk_0)("CLK");
  (mkTB1_instance->set_clk_0)("CLK");
}
void MODEL_mkTB1::destroy_model()
{
  delete mkTB1_instance;
  mkTB1_instance = NULL;
}
void MODEL_mkTB1::reset_model(bool asserted)
{
  (mkTB1_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkTB1::get_instance()
{
  return mkTB1_instance;
}

/* Fill in version numbers */
void MODEL_mkTB1::get_version(char const **name, char const **build)
{
  *name = "2023.07";
  *build = "0eb551dc";
}

/* Get the model creation time */
time_t MODEL_mkTB1::get_creation_time()
{
  
  /* Wed Feb 14 17:26:12 UTC 2024 */
  return 1707931572llu;
}

/* State dumping function */
void MODEL_mkTB1::dump_state()
{
  (mkTB1_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkTB1 & mkTB1_backing(tSimStateHdl simHdl)
{
  static MOD_mkTB1 *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkTB1(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkTB1::dump_VCD_defs()
{
  (mkTB1_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkTB1::dump_VCD(tVCDDumpType dt)
{
  (mkTB1_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkTB1_backing(sim_hdl));
}
