/*
 * Generated by Bluespec Compiler, version 2023.07 (build 0eb551dc)
 * 
 * On Tue Feb 13 17:46:46 CET 2024
 * 
 */

/* Generation options: */
#ifndef __mkTXSR_h__
#define __mkTXSR_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkTXSR module */
class MOD_mkTXSR : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Fifo<tUInt8> INST_fTX;
  MOD_Wire<tUInt8> INST_pwTick;
  MOD_Reg<tUInt8> INST_rBitIndex;
  MOD_Reg<tUInt32> INST_rCounter;
  MOD_Reg<tUInt32> INST_rOut;
  MOD_Reg<tUInt8> INST_rOutputPin;
 
 /* Constructor */
 public:
  MOD_mkTXSR(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
 
 /* Rules */
 public:
  void RL_tick_gen();
  void RL_send_bit();
 
 /* Methods */
 public:
  tUInt8 METH_pin();
  tUInt8 METH_RDY_pin();
  void METH_data_put(tUInt8 ARG_data_put);
  tUInt8 METH_RDY_data_put();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTXSR &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTXSR &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTXSR &backing);
};

#endif /* ifndef __mkTXSR_h__ */
